Update logrotate to 3.0.0
osuosl-cookbooks/osl-nginx pull request #41
Opened 2021-10-19 22:52 UTC by EMH333

Must release along side other `logrotate` updates. Had to change the spec test because of `logrotate` cookbook internals

2021-10-19 23:44 UTC, ramereth requested changes

2021-10-19 23:44 UTC, ramereth commented on recipes/logrotate.rb
> +logrotate_package 'logrotate'
```suggestion
logrotate_package 'osl-nginx'
```

2021-11-02 15:59 UTC, EMH333 commented
!bump minor ~

2021-11-02 16:00 UTC, merged

2021-11-02 16:00 UTC, osuosl-manatee commented
Jenkins has merged this PR into `master` and has automatically performed a minor-level version bump to v6.3.0.  Have a nice day!